#local_backend: true
backend:
  name: github
  repo: setyabun/catatan-bun
  branch: main
  base_url: https://decap-cms-oauth.vercel.app
#  proxy_url: http://localhost:8081/api/v1 # Ini tetap di sini sebagai cadangan

# Folder untuk menyimpan gambar yang kamu upload via CMS
media_folder: "static/images" 
public_folder: "/images"

collections:
  - name: "blog"
    label: "Postingan Blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Isi Catatan", name: "body", widget: "markdown"}
